-- Creating Sequence for customer
CREATE SEQUENCE customer_seq
START WITH 1
INCREMENT BY 1;

-- Creating the main Customer table
CREATE TABLE CUSTOMER (
    ID NUMBER(12) PRIMARY KEY,
    FIRSTNAME VARCHAR2(255 CHAR),
    LASTNAME VARCHAR2(255 CHAR),
    OFFICE_EMAIL VARCHAR2(255 CHAR),
    PERSONAL_EMAIL VARCHAR2(255 CHAR)
);

-- Creating table for family members (ElementCollection)
CREATE TABLE CUSTOMER_FAMILY_MEMBERS (
    CUSTOMER_ID NUMBER(12) REFERENCES CUSTOMER(ID),
    FAMILY_MEMBER_NAME VARCHAR2(255 CHAR)
);
